### ISSUE TITLE
[Feature Request] comment-changes: Check comments both body and summary for keywords

### ISSUE THREAD

**Issue by AmmarAbouZor** [kevinmatthes/aeruginous-rs#337]
It would be useful to give the users the flexibility to use both options 'Squash and merge' and  the normal merge PR in their repos and still have all of them documented properly with Aeruginous by creating a logic to make it intelligently choose the right source to analyze from.

The logic I have in mind is to search for the categories in both comment's  summery and  body and choose the one that contains one of the categories. And if not it will fallback to body if the -b flag is active or to summery otherwise.

For that we can add a new argument like `--intelligent_search` which can be combined with `--body` and `--fallback_category`

**Comment by kevinmatthes** [comment]
Thank you for this suggestion, @AmmarAbouZor!  I will consider this for the next feature release!

The very next release will bring two new modes (a version incrementing system as well as a CLI version of https://github.com/kevinmatthes/cff-release-today) which are going to form v2.2.0.  The feature you requested will be part of the succeeding version, I assume v2.3.0.

**Comment by kevinmatthes** [comment]
Please do not be confused:  I just released an intermediate patch version which introduces my solution to #336.  The reason therefore is that I noticed in certain minor bug in the release workflow of TUI-Journal for which I would like to present you a working solution together with the report.  I am going to draft the corresponding bug report in a moment.

The solution to #337 is already in development and will be part of the next minor release.

**Comment by AmmarAbouZor** [comment]
Thanks for the clarification and please take your time with it.
Currently, I can switch between squash and merge and the normal merge and it's working fine :+1:

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

The new version 3.0.2 is release to crates.io!  See #501 for details.
